openapi: 3.0.0
info:
  title: Good Night API
  version: 1.0.0
servers:
  - url: localhost:3000
tags:
  - name: Follows Controller
  - name: Sleep Records Controller
  - name: Friend Sleep Records
paths:
  /api/v1/follows:
    post:
      tags:
        - Follows Controller
      summary: Follow a User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 2
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Follow' 
  /api/v1/follows/2:
    delete:
      tags:
        - Follows Controller
      summary: Unfollow a friend
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/sleep_records:
    post:
      tags:
        - Sleep Records Controller
      summary: Create a Sleep Record of User 3
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                start_time: '2023-03-06 23:00:00'
                end_time: '2023-03-07 06:00:00'
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/SleepRecord' 
    get:
      tags:
        - Sleep Records Controller
      summary: Get Sleep Records
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SleepRecords'             
  /api/v1/sleep_records/2:
    put:
      tags:
        - Sleep Records Controller
      summary: Update a Sleep Record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                end_time: '2023-03-04 06:00:00'
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SleepRecord'             
  /api/v1/friends/sleep_records:
    get:
      tags:
        - Friend Sleep Records
      summary: Get Friend Sleep Records
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SleepRecord'             

components:
  schemas:
    Follow:
        properties:
          id: 
            type: integer
            format: int32
            example: 1
          following_id: 
            type: integer
            format: int32
            example: 1
          follower_id: 
            type: integer
            format: int32
            example: 2
    SleepRecord:
      properties:
        id: 
          type: integer
          format: int32
          example: 1
        start_time: 
          type: string
          example: "2023-03-03T23:00:00.000Z"
        end_time: 
          type: string
          example: "2023-03-04T06:00:00.000Z"    
    SleepRecords:
      properties:
        sleep_records:
          type: array
          items: 
            type: object
            properties: 
              id: 
                type: integer
                format: int32
                example: 1
              start_time: 
                type: string
                example: "2023-03-03T23:00:00.000Z"
              end_time: 
                type: string
                example: "2023-03-04T06:00:00.000Z"
                format: nullable
        pagination: 
          type: object
          properties: 
            current: 
              type: integer
              format: int32
            previous: 
              type: string
              format: nullable
            next: 
              type: string
              format: nullable
            per_page: 
              type: integer
              format: int32
            count: 
              type: integer
              format: int32

